version: '3'
services:
  kali-linux:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ctf-kali
    volumes:
      - $HOME/Works:/root/Works
      - $HOME/Downloads:/root/Downloads
      - $HOME/.ssh:/root/.ssh
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file:
      - .env
    environment:
      # for xserver with xquartz
      - DISPLAY=${IP}:0
    tty: true
    stdin_open: true
    command: >
      /bin/zsh
